// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/ip-geolocation-api4-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"advanced | api_usage_stats_model | api_usage_summary | asn | batch | batch_email_validation_response_dto | cache_management | domain_analysi | domain_reputation_v1_dto | email | forward | ip_info_v0 | ip_reputation | ipn | ipn2 | mxn | paddle_controller | rate_limit_info_dto | reverse | risk_score | status | tor | usage_statistic | whoi"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.IpGeolocationApi4SDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "ip-geolocation-api4_list",
		Description: "List records from IpGeolocationApi4. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "ip-geolocation-api4_load",
		Description: "Load a single record from IpGeolocationApi4. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.IpGeolocationApi4SDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IpGeolocationApi4SDK, name string) (sdk.IpGeolocationApi4Entity, error) {
	switch strings.ToLower(name) {
	case "advanced":
		return client.Advanced(nil), nil
	case "api_usage_stats_model":
		return client.ApiUsageStatsModel(nil), nil
	case "api_usage_summary":
		return client.ApiUsageSummary(nil), nil
	case "asn":
		return client.Asn(nil), nil
	case "batch":
		return client.Batch(nil), nil
	case "batch_email_validation_response_dto":
		return client.BatchEmailValidationResponseDto(nil), nil
	case "cache_management":
		return client.CacheManagement(nil), nil
	case "domain_analysi":
		return client.DomainAnalysi(nil), nil
	case "domain_reputation_v1_dto":
		return client.DomainReputationV1Dto(nil), nil
	case "email":
		return client.Email(nil), nil
	case "forward":
		return client.Forward(nil), nil
	case "ip_info_v0":
		return client.IpInfoV0(nil), nil
	case "ip_reputation":
		return client.IpReputation(nil), nil
	case "ipn":
		return client.Ipn(nil), nil
	case "ipn2":
		return client.Ipn2(nil), nil
	case "mxn":
		return client.Mxn(nil), nil
	case "paddle_controller":
		return client.PaddleController(nil), nil
	case "rate_limit_info_dto":
		return client.RateLimitInfoDto(nil), nil
	case "reverse":
		return client.Reverse(nil), nil
	case "risk_score":
		return client.RiskScore(nil), nil
	case "status":
		return client.Status(nil), nil
	case "tor":
		return client.Tor(nil), nil
	case "usage_statistic":
		return client.UsageStatistic(nil), nil
	case "whoi":
		return client.Whoi(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
